# Generated by Django 5.2.7 on 2025-10-22 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sport_category', models.CharField(choices=[('soccer', 'Soccer'), ('tennis', 'Tennis'), ('badminton', 'Badminton'), ('futsal', 'Futsal'), ('basket', 'Basket'), ('multi', 'Multi-sport')], max_length=20)),
                ('owner_name', models.CharField(max_length=100)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
