# Generated by Django 5.2.7 on 2025-10-25 10:41

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sport_category', models.CharField(choices=[('soccer', 'Soccer'), ('tennis', 'Tennis'), ('badminton', 'Badminton'), ('futsal', 'Futsal'), ('basket', 'Basket'), ('multi', 'Multi-sport')], max_length=20)),
                ('region', models.CharField(choices=[('jakarta_pusat', 'Jakarta Pusat'), ('jakarta_selatan', 'Jakarta Selatan'), ('jakarta_barat', 'Jakarta Barat'), ('jakarta_timur', 'Jakarta Timur'), ('jakarta_utara', 'Jakarta Utara')], max_length=30)),
                ('quantity', models.PositiveIntegerField()),
                ('available', models.BooleanField(default=True)),
                ('thumbnail', models.URLField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['price_per_hour'],
            },
        ),
    ]
