# Generated by Django 5.2.7 on 2025-10-23 02:40

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ['price_per_hour']},
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='description',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='owner_name',
        ),
        migrations.AddField(
            model_name='equipment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='equipment',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='equipment',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='equipment',
            name='region',
            field=models.CharField(choices=[('jakarta_pusat', 'Jakarta Pusat'), ('jakarta_selatan', 'Jakarta Selatan'), ('jakarta_barat', 'Jakarta Barat'), ('jakarta_timur', 'Jakarta Timur'), ('jakarta_utara', 'Jakarta Utara')], default='jakarta_selatan', max_length=30),
        ),
        migrations.AddField(
            model_name='equipment',
            name='thumbnail',
            field=models.URLField(default='https://via.placeholder.com/190'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(max_length=120),
        ),
    ]
