# Generated by Django 5.2.7 on 2025-10-23 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_alter_equipment_options_remove_equipment_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='region',
            field=models.CharField(choices=[('jakarta_pusat', 'Jakarta Pusat'), ('jakarta_selatan', 'Jakarta Selatan'), ('jakarta_barat', 'Jakarta Barat'), ('jakarta_timur', 'Jakarta Timur'), ('jakarta_utara', 'Jakarta Utara')], max_length=30),
        ),
    ]
