# Generated by Django 5.2.7 on 2025-10-16 18:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('football', 'Football'), ('tennis', 'Tennis'), ('futsal', 'Futsal'), ('badminton', 'Badminton'), ('basketball', 'Basketball')], default='update', max_length=20)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('venue_views', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
    ]
