# Generated by Django 5.2.7 on 2025-10-17 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='capacity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venue',
            name='time',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='category',
            field=models.CharField(choices=[('soccer', 'Soccer'), ('tennis', 'Tennis'), ('futsal', 'Futsal'), ('badminton', 'Badminton'), ('basketball', 'Basketball')], default='update', max_length=20),
        ),
    ]
