# Generated by Django 5.2.7 on 2025-10-23 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_booking_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='borrower_name',
            field=models.CharField(default='Unknown', help_text='Nama orang yang akan menggunakan lapangan', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.PositiveIntegerField(blank=True, help_text='Otomatis dihitung dari durasi × harga venue', null=True),
        ),
    ]
