# Generated by Django 5.2.7 on 2025-10-22 07:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('category', models.CharField(choices=[('soccer', 'Soccer'), ('tennis', 'Tennis'), ('badminton', 'Badminton'), ('basketball', 'Basketball'), ('futsal', 'Futsal'), ('other', 'Other')], default='other', max_length=20)),
                ('address', models.TextField(blank=True)),
                ('price', models.PositiveIntegerField(blank=True, help_text='Rupiah per hour', null=True)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('opening_time', models.TimeField(blank=True, null=True)),
                ('closing_time', models.TimeField(blank=True, null=True)),
                ('time_display', models.CharField(blank=True, help_text='Freeform time range text', max_length=50)),
                ('thumbnail', models.CharField(blank=True, help_text='Image filename or URL', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['category'], name='main_venue_categor_227160_idx'), models.Index(fields=['price'], name='main_venue_price_73dba1_idx')],
                'unique_together': {('name', 'address')},
            },
        ),
    ]
