# Generated by Django 5.2.7 on 2025-10-25 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('category', models.CharField(choices=[('soccer', 'Soccer'), ('tennis', 'Tennis'), ('badminton', 'Badminton'), ('futsal', 'Futsal'), ('basketball', 'Basketball'), ('multi-sport', 'Multi-Sport'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.TextField(blank=True, help_text='A short description of the venue.')),
                ('address', models.TextField(blank=True)),
                ('price', models.PositiveIntegerField(blank=True, help_text='Price in Rupiah per hour (e.g., 50000)', null=True)),
                ('capacity', models.PositiveIntegerField(blank=True, help_text='Maximum number of people', null=True)),
                ('opening_time', models.TimeField(blank=True, null=True)),
                ('closing_time', models.TimeField(blank=True, null=True)),
                ('time_display', models.CharField(blank=True, editable=False, max_length=50)),
                ('thumbnail', models.CharField(blank=True, help_text='e.g., my_venue.jpg or a URL https://...', max_length=200)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='venues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['category'], name='main_venue_categor_227160_idx'), models.Index(fields=['price'], name='main_venue_price_73dba1_idx')],
                'unique_together': {('name', 'address')},
            },
        ),
    ]
