# Generated by Django 5.2.7 on 2025-10-23 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_venue_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='description',
            field=models.TextField(blank=True, help_text='A short description of the venue.'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of people', null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='category',
            field=models.CharField(choices=[('soccer', 'Soccer'), ('tennis', 'Tennis'), ('badminton', 'Badminton'), ('futsal', 'Futsal'), ('basketball', 'Basketball'), ('multi-sport', 'Multi-Sport'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='venue',
            name='price',
            field=models.PositiveIntegerField(blank=True, help_text='Price in Rupiah per hour (e.g., 50000)', null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='thumbnail',
            field=models.CharField(blank=True, help_text='e.g., my_venue.jpg or a URL https://...', max_length=200),
        ),
        migrations.AlterField(
            model_name='venue',
            name='time_display',
            field=models.CharField(blank=True, editable=False, max_length=50),
        ),
    ]
