# Generated by Django 5.2.7 on 2025-10-23 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_venue_description_alter_venue_capacity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='description',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='is_featured',
        ),
        migrations.AlterField(
            model_name='venue',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='category',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='venue',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='venue',
            name='time_display',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
