# Generated by Django 5.2.7 on 2025-10-22 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='image_url',
            field=models.URLField(blank=True, help_text='(opsional)', max_length=2000, null=True),
        ),
    ]
