# Generated by Django 5.2.7 on 2025-10-25 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_reviews_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='sport_type',
            field=models.CharField(choices=[('soccer', 'Soccer'), ('tennis', 'Tennis'), ('badminton', 'Badminton'), ('futsal', 'Futsal'), ('basket', 'Basket')], default='soccer', max_length=20),
        ),
    ]
